# Generated by Django 2.2 on 2019-04-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='price',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
